version: '3.8'

services:
  # Echo servers (backend targets)
  echo-server-1:
    build:
      context: ..
      dockerfile: benchmark/Dockerfile.echo-server
    container_name: echo-server-1
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_ID=1
    networks:
      - benchmark-network

  echo-server-2:
    build:
      context: ..
      dockerfile: benchmark/Dockerfile.echo-server
    container_name: echo-server-2
    ports:
      - "8082:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_ID=2
    networks:
      - benchmark-network

  echo-server-3:
    build:
      context: ..
      dockerfile: benchmark/Dockerfile.echo-server
    container_name: echo-server-3
    ports:
      - "8083:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_ID=3
    networks:
      - benchmark-network

  # BunGate API Gateway
  bungate:
    build:
      context: ..
      dockerfile: benchmark/Dockerfile.bungate
    container_name: bungate
    ports:
      - "3000:3000"
    depends_on:
      - echo-server-1
      - echo-server-2
      - echo-server-3
    environment:
      - GATEWAY_PORT=3000
      - TARGETS=http://echo-server-1:8080,http://echo-server-2:8080,http://echo-server-3:8080
    networks:
      - benchmark-network

  # Nginx API Gateway
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "3001:80"
    depends_on:
      - echo-server-1
      - echo-server-2
      - echo-server-3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - benchmark-network

  # Envoy API Gateway
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    container_name: envoy
    ports:
      - "3002:8080"
    depends_on:
      - echo-server-1
      - echo-server-2
      - echo-server-3
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml"]
    networks:
      - benchmark-network

  # wrk benchmark tool
  wrk:
    build:
      context: .
      dockerfile: Dockerfile.wrk
    container_name: wrk
    depends_on:
      - bungate
      - nginx
      - envoy
    volumes:
      - ./results:/results
      - ./scripts:/scripts
    networks:
      - benchmark-network
    command: ["tail", "-f", "/dev/null"]  # Keep container running

networks:
  benchmark-network:
    driver: bridge
